# Generated by Django 6.0.2 on 2026-03-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_interaccion_usuario_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
