# Generated by Django 6.0.2 on 2026-03-25 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_token_verificacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compromiso',
            old_name='id_actividad',
            new_name='interaccion',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='id_tipo_contacto',
            new_name='tipo_contacto',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='id_tipo_doc',
            new_name='tipo_doc',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='id_usuario_asignado',
            new_name='usuario_asignado',
        ),
        migrations.RenameField(
            model_name='interaccion',
            old_name='id_contacto',
            new_name='contacto',
        ),
        migrations.RenameField(
            model_name='interaccion',
            old_name='id_tipo_interaccion',
            new_name='tipo_interaccion',
        ),
        migrations.RemoveField(
            model_name='interaccion',
            name='id_usuario_responsable',
        ),
        migrations.AddField(
            model_name='contacto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='historial_cambios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interaccion',
            name='asunto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interaccion',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interaccion',
            name='direccion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='interaccion',
            name='estado',
            field=models.CharField(default='Finalizada', max_length=20),
        ),
        migrations.AddField(
            model_name='interaccion',
            name='fecha_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interaccion',
            name='fecha_reunion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interaccion',
            name='historial_cambios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interaccion',
            name='hora_reunion',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interaccion',
            name='mensaje_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interaccion',
            name='modalidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interaccion',
            name='tipo_comunicacion',
            field=models.CharField(default='Saliente', max_length=10),
        ),
        migrations.AddField(
            model_name='interaccion',
            name='usuario_responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='token_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
