# Generated by Django 6.0.2 on 2026-04-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_id_actividad_compromiso_interaccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaccion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
