# Generated by Django 6.0.3 on 2026-03-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rol_usuario_alter_contacto_usuario_asignado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaccion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
