# Generated by Django 6.0.3 on 2026-03-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_interaccion_fecha_actualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaccion',
            name='tipo_comunicacion',
            field=models.CharField(choices=[('Entrante', 'Entrante'), ('Saliente', 'Saliente')], default='Saliente', max_length=10),
        ),
    ]
