# Generated by Django 6.0.3 on 2026-03-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_interaccion_tipo_comunicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaccion',
            name='mensaje_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
