# Generated by Django 6.0.2 on 2026-06-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mensajewhatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nuevo_email_pendiente',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='token_cambio_email',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='token_cambio_email_expiracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
