# Generated by Django 6.0.3 on 2026-03-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_interaccion_mensaje_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaccion',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    ]
