# Generated by Django 6.0.3 on 2026-03-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_interaccion_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaccion',
            name='estado',
            field=models.CharField(choices=[('Programada', 'Programada'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada')], default='Finalizada', max_length=20),
        ),
    ]
