# Generated by Django 6.0.3 on 2026-03-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_interaccion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaccion',
            name='modalidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
