# Generated by Django 6.0.3 on 2026-03-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_interaccion_modalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaccion',
            name='asunto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interaccion',
            name='fecha_reunion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interaccion',
            name='hora_reunion',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
