# Generated by Django 6.0.3 on 2026-03-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_interaccion_asunto_interaccion_fecha_reunion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaccion',
            name='direccion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
