# Generated by Django 6.0.3 on 2026-03-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_interaccion_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaccion',
            name='historial_cambios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
