# Generated by Django 6.0.2 on 2026-03-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_interaccion_historial_cambios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='token_verificacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
