# Generated by Django 6.0.2 on 2026-03-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_usuario_token_verificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='token_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
