"""Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-9nqyhnj14&rheqfwrhkt#7*&d#o3oqm$^!-c)cn3i+ky=c60n-')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '10.6.76.127', '.ngrok-free.dev']
ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    '.ngrok-free.dev',
    '.onrender.com',
]

RENDER_EXTERNAL_HOST = os.getenv('RENDER_EXTERNAL_HOST')
if RENDER_EXTERNAL_HOST:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOST)

NGROK_URL = os.getenv('NGROK_URL', 'https://karly-nonwarrantable-letty.ngrok-free.dev')

ALLOWED_HOSTS = ['*']
NGROK_URL = 'https://karly-nonwarrantable-letty.ngrok-free.dev'
CSRF_TRUSTED_ORIGINS = [NGROK_URL, 'https://*.ngrok-free.dev']
RENDER_EXTERNAL_URL = os.getenv('RENDER_EXTERNAL_URL')
if RENDER_EXTERNAL_URL:
    CSRF_TRUSTED_ORIGINS.append(RENDER_EXTERNAL_URL)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'Pruebas'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'db_dyco',
#         'USER': 'postgres',
#         'PASSWORD': '1234',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }

DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///db.sqlite3'
    )
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-co'
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Configuración de Envío de Correos (Brevo API)
BREVO_API_KEY = os.getenv('BREVO_API_KEY', 'xkeysib-a2824e43cc50d164148add8edb977446cd824a648f21ee458f5592f830b1e1b-bgxcr4S3hWANgD6i')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'dsolutions918@gmail.com')

EMAIL_BACKEND = 'core.email_backend.BrevoEmailBackend'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')

# Configuración IMAP (Recibir Correos)
IMAP_HOST = 'imap.gmail.com'
IMAP_PORT = 993

# Configuración de Archivos Media (Subidas)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# config/settings.py

WHATSAPP_ACCESS_TOKEN = os.getenv('WHATSAPP_ACCESS_TOKEN', '')
WHATSAPP_PHONE_NUMBER_ID = os.getenv('WHATSAPP_PHONE_NUMBER_ID', '')
WHATSAPP_VERIFY_TOKEN = os.getenv('WHATSAPP_VERIFY_TOKEN', 'pato_123')

# UltraMsg para WhatsApp (alternativa simple a Meta API)
ULTRAMSG_INSTANCE_ID = os.getenv('ULTRAMSG_INSTANCE_ID', 'instance180529')
ULTRAMSG_TOKEN = os.getenv('ULTRAMSG_TOKEN', 'c8z7umlwaefy1agx')

import sys
if 'runserver' in sys.argv or 'gunicorn' in sys.argv:
    host = os.getenv('RENDER_EXTERNAL_HOSTNAME', 'TU-DOMINIO')
    print(f"\n[CONFIG] BREVO_API_KEY={'✓ definido' if BREVO_API_KEY else '✗ VACÍO'}")
    print(f"[CONFIG] DEFAULT_FROM_EMAIL={DEFAULT_FROM_EMAIL}")
    print(f"[CONFIG] WHATSAPP (Meta)={'✓' if os.getenv('WHATSAPP_ACCESS_TOKEN') else '✗'} | UltraMsg={'✓' if os.getenv('ULTRAMSG_TOKEN') else '✗'}")
    if os.getenv('ULTRAMSG_TOKEN'):
        print(f"[CONFIG] Webhook UltraMsg: https://{host}/ultramsg-webhook/")
    else:
        print(f"[CONFIG] Webhook URL: https://{host}/whatsapp-webhook/\n")
